version: '3.8'

services:
  laravel:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      - POSTGRES_USER=prova_digiliza
      - POSTGRES_PASSWORD=pRoV4_D1g1l1Z4
      - POSTGRES_DB=prova_digiliza
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  vuejs:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vuejs-app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: ["npm", "run", "dev"]

volumes:
  pg_data:
